language: python
services:
  - docker
python:
  - "2.7"
inslall:
  - make deps
script:
  - make lint
  - make test_xunit
  - make docker_build
  - make docker_push
deploy:
    provider: heroku
    app: still-ridge-87834
    api_key: ${HEROKU_API_KEY}
